const CANVAS_BORDER_COLOR = { RED: '#FF0000', GREEN: '#00FF00' };
const INDEX_OFFSET = 1;
const DEFAULT_REQUEST_WORDS_NUMBER = 20;
const MISSING_PAINTINGS_DATA_OFFSET = 40;
const SHORT_WORDS_MAX_LENGTH = 3;
const LONG_WORDS_MIN_LENGTH = 6;

const CONSTANTS = {
  CANVAS_BORDER_COLOR,
  INDEX_OFFSET,
  DEFAULT_REQUEST_WORDS_NUMBER,
  MISSING_PAINTINGS_DATA_OFFSET,
  SHORT_WORDS_MAX_LENGTH,
  LONG_WORDS_MIN_LENGTH,
};

export default CONSTANTS;
