const CANVAS_COLORS = { RED: '#FF0000', GREEN: '#00FF00', WHITE: '#FFFFFF' };
const INDEX_OFFSET = 1;
const DEFAULT_REQUEST_WORDS_NUMBER = 20;
const MISSING_PAINTINGS_DATA_OFFSET = 40;
const SHORT_WORDS_MAX_LENGTH = 3;
const LONG_WORDS_MIN_LENGTH = 6;
const DEFAULT_PUZZLE_SHIRT_COLOR = '#1C283B';
const DEFAULT_PUZZLE_CLIP_LENGTH = 16;
const MAX_SENTENCES_COUNT = 10;
const PUZZLE_HEIGHT = 50;
const MAX_GAME_LEVEL = 60;
const MAX_GAME_DIFFICULT = 6;

const CONSTANTS = {
  CANVAS_COLORS,
  INDEX_OFFSET,
  DEFAULT_REQUEST_WORDS_NUMBER,
  MISSING_PAINTINGS_DATA_OFFSET,
  SHORT_WORDS_MAX_LENGTH,
  LONG_WORDS_MIN_LENGTH,
  DEFAULT_PUZZLE_SHIRT_COLOR,
  DEFAULT_PUZZLE_CLIP_LENGTH,
  MAX_SENTENCES_COUNT,
  PUZZLE_HEIGHT,
  MAX_GAME_LEVEL,
  MAX_GAME_DIFFICULT,
};

export default CONSTANTS;
