const CANVAS_BORDER_COLOR = { RED: '#FF0000', GREEN: '#00FF00' };
const INDEX_OFFSET = 1;
const DEFAULT_REQUEST_WORDS_NUMBER = 20;

const CONSTANTS = {
  CANVAS_BORDER_COLOR,
  INDEX_OFFSET,
  DEFAULT_REQUEST_WORDS_NUMBER,
};

export default CONSTANTS;
