const MODEL = {
  language: ['en', 'ru'],
  title: 'Virtual Keyboard',
  legend: ['OS Windows', 'You can change language press Ctrl + Alt'],
  specialBtn: [
    'Backspace',
    'Tab',
    'Delete',
    'CapsLock',
    'Enter',
    'ShiftLeft',
    'ShiftRight',
    'ControlLeft',
    'ControlRight',
    'AltLeft',
    'AltRight',
    'MetaLeft',
    'ArrowLeft',
    'ArrowRight',
    'ArrowUp',
    'ArrowDown',
  ],
  en: [
    {
      Backquote: ['`', '~'],
      Digit1: ['1', '!'],
      Digit2: ['2', '@'],
      Digit3: ['3', '#'],
      Digit4: ['4', '$'],
      Digit5: ['5', '%'],
      Digit6: ['6', '^'],
      Digit7: ['7', '&'],
      Digit8: ['8', '*'],
      Digit9: ['9', '('],
      Digit0: ['0', ')'],
      Minus: ['-', '_'],
      Equal: ['=', '+'],
      Backspace: [],
    },
    {
      Tab: [],
      KeyQ: ['q', 'Q'],
      KeyW: ['w', 'W'],
      KeyE: ['e', 'E'],
      KeyR: ['r', 'R'],
      KeyT: ['t', 'T'],
      KeyY: ['y', 'Y'],
      KeyU: ['u', 'U'],
      KeyI: ['i', 'I'],
      KeyO: ['o', 'O'],
      KeyP: ['p', 'P'],
      BracketLeft: ['[', '{'],
      BracketRight: [']', '}'],
      Backslash: ['\\', '|'],
      Delete: ['Del', 'Del'],
    },
    {
      CapsLock: [],
      KeyA: ['a', 'A'],
      KeyS: ['s', 'S'],
      KeyD: ['d', 'D'],
      KeyF: ['f', 'F'],
      KeyG: ['g', 'G'],
      KeyH: ['h', 'H'],
      KeyJ: ['j', 'J'],
      KeyK: ['k', 'K'],
      KeyL: ['l', 'L'],
      Semicolon: [';', ':'],
      Quote: ["'", '"'],
      Enter: [],
    },
    {
      ShiftLeft: ['Shift', 'Shift'],
      KeyZ: ['z', 'Z'],
      KeyX: ['x', 'X'],
      KeyC: ['c', 'C'],
      KeyV: ['v', 'V'],
      KeyB: ['b', 'B'],
      KeyN: ['n', 'N'],
      KeyM: ['m', 'M'],
      Comma: [',', '<'],
      Period: ['.', '>'],
      Slash: ['/', '?'],
      ArrowUp: ['&#9650;', '&#9650;'],
      ShiftRight: ['Shift', 'Shift'],
    },
    {
      ControlLeft: ['Ctrl', 'Ctrl'],
      MetaLeft: ['RU', 'RU'],
      AltLeft: ['Alt', 'Alt'],
      Space: [' ', ' '],
      AltRight: ['Alt', 'Alt'],
      ArrowLeft: ['&#9668;', '&#9668;'],
      ArrowDown: ['&#9660;', '&#9660;'],
      ArrowRight: ['&#9658;', '&#9658;'],
      ControlRight: ['Ctrl', 'Ctrl'],
    },
  ],

  ru: [
    {
      Backquote: ['ё', 'Ё'],
      Digit1: ['1', '!'],
      Digit2: ['2', '"'],
      Digit3: ['3', '№'],
      Digit4: ['4', ';'],
      Digit5: ['5', '%'],
      Digit6: ['6', ':'],
      Digit7: ['7', '?'],
      Digit8: ['8', '*'],
      Digit9: ['9', '('],
      Digit0: ['0', ')'],
      Minus: ['-', '_'],
      Equal: ['=', '+'],
      Backspace: [],
    },
    {
      Tab: [],
      KeyQ: ['й', 'Й'],
      KeyW: ['ц', 'Ц'],
      KeyE: ['у', 'У'],
      KeyR: ['к', 'К'],
      KeyT: ['е', 'Е'],
      KeyY: ['н', 'Н'],
      KeyU: ['г', 'Г'],
      KeyI: ['ш', 'Ш'],
      KeyO: ['ш', 'Щ'],
      KeyP: ['щ', 'З'],
      BracketLeft: ['х', 'Х'],
      BracketRight: ['ъ', 'Ъ'],
      Backslash: ['\\', '/'],
      Delete: ['Del', 'Del'],
    },
    {
      CapsLock: [],
      KeyA: ['ф', 'Ф'],
      KeyS: ['ы', 'Ы'],
      KeyD: ['в', 'В'],
      KeyF: ['а', 'А'],
      KeyG: ['п', 'П'],
      KeyH: ['р', 'Р'],
      KeyJ: ['о', 'О'],
      KeyK: ['л', 'Л'],
      KeyL: ['д', 'Д'],
      Semicolon: ['ж', 'Ж'],
      Quote: ['э', 'Э'],
      Enter: [],
    },
    {
      ShiftLeft: ['Shift', 'Shift'],
      KeyZ: ['я', 'Я'],
      KeyX: ['ч', 'Ч'],
      KeyC: ['с', 'С'],
      KeyV: ['м', 'М'],
      KeyB: ['и', 'И'],
      KeyN: ['т', 'Т'],
      KeyM: ['ь', 'Ь'],
      Comma: ['б', 'Б'],
      Period: ['ю', 'Ю'],
      Slash: ['.', ','],
      ArrowUp: ['&#9650;', '&#9650;'],
      ShiftRight: ['Shift', 'Shift'],
    },
    {
      ControlLeft: ['Ctrl', 'Ctrl'],
      MetaLeft: ['EN', 'EN'],
      AltLeft: ['Alt', 'Alt'],
      Space: [' ', ' '],
      AltRight: ['Alt', 'Alt'],
      ArrowLeft: ['&#9668;', '&#9668;'],
      ArrowDown: ['&#9660;', '&#9660;'],
      ArrowRight: ['&#9658;', '&#9658;'],
      ControlRight: ['Ctrl', 'Ctrl'],
    },
  ],
};

export default MODEL;
