const MIN_GAME_POINTS = 10;
const MAX_GAME_POINTS = 80;
const VALUE_TO_SWITCH = 4;
const GAME_TIME = 60;
const CORRECT_SOUND = 'correct.mp3';
const ERROR_SOUND = 'error.mp3';
const COUNTDOWN_DELAY = 1000;
const ANSWER_ANIMATION_DELAY = 200;

export {
  MIN_GAME_POINTS,
  MAX_GAME_POINTS,
  VALUE_TO_SWITCH,
  GAME_TIME,
  CORRECT_SOUND,
  ERROR_SOUND,
  COUNTDOWN_DELAY,
  ANSWER_ANIMATION_DELAY,
};
