const GAME_DATA = [
  {
    id: '5e9f5ee35eb9e72bc21af4c8',
    group: 0,
    page: 2,
    word: 'alien',
    image: 'files/03_0041.jpg',
    audio: 'files/03_0041.mp3',
    audioMeaning: 'files/03_0041_meaning.mp3',
    audioExample: 'files/03_0041_example.mp3',
    textMeaning: 'An <i>alien</i> is a creature from a different world.',
    textExample: 'The <b>alien</b> came in peace.',
    transcription: '[éiljən]',
    textExampleTranslate: 'пришелец пришел с миром',
    textMeaningTranslate: 'Инопланетянин - это существо из другого мира',
    wordTranslate: 'инопланетянин',
    wordsPerExampleSentence: 5,
  },
  {
    id: '5e9f5ee35eb9e72bc21af4c9',
    group: 0,
    page: 2,
    word: 'among',
    image: 'files/03_0042.jpg',
    audio: 'files/03_0042.mp3',
    audioMeaning: 'files/03_0042_meaning.mp3',
    audioExample: 'files/03_0042_example.mp3',
    textMeaning: 'If you are <i>among</i> certain things, they are all around you.',
    textExample: 'There was a red apple <b>among</b> the green ones.',
    transcription: '[əmʌ̀ŋ]',
    textExampleTranslate: 'Среди зеленых было красное яблоко',
    textMeaningTranslate: 'Если вы среди определенных вещей, они все вокруг вас',
    wordTranslate: 'среди',
    wordsPerExampleSentence: 9,
  },
  {
    id: '5e9f5ee35eb9e72bc21af4ca',
    group: 0,
    page: 2,
    word: 'chart',
    image: 'files/03_0043.jpg',
    audio: 'files/03_0043.mp3',
    audioMeaning: 'files/03_0043_meaning.mp3',
    audioExample: 'files/03_0043_example.mp3',
    textMeaning: 'A <i>chart</i> is a list of information.',
    textExample: 'We used a <b>chart</b> to see how we had improved.',
    transcription: '[tʃɑːrt]',
    textExampleTranslate: 'Мы использовали график, чтобы увидеть, как мы улучшили',
    textMeaningTranslate: 'Диаграмма - это список информации',
    wordTranslate: 'диаграмма',
    wordsPerExampleSentence: 10,
  },
  {
    id: '5e9f5ee35eb9e72bc21af4cb',
    group: 0,
    page: 2,
    word: 'cloud',
    image: 'files/03_0044.jpg',
    audio: 'files/03_0044.mp3',
    audioMeaning: 'files/03_0044_meaning.mp3',
    audioExample: 'files/03_0044_example.mp3',
    textMeaning: 'A <i>cloud</i> is a group of water drops in the sky.',
    textExample: 'The sky was filled with white <b>clouds</b>.',
    transcription: '[klaud]',
    textExampleTranslate: 'Небо было наполнено белыми облаками',
    textMeaningTranslate: 'Облако - это группа капель воды в небе',
    wordTranslate: 'облако',
    wordsPerExampleSentence: 7,
  },
  {
    id: '5e9f5ee35eb9e72bc21af4cc',
    group: 0,
    page: 2,
    word: 'describe',
    image: 'files/03_0045.jpg',
    audio: 'files/03_0045.mp3',
    audioMeaning: 'files/03_0045_meaning.mp3',
    audioExample: 'files/03_0045_example.mp3',
    textMeaning: 'To <i>describe</i> is to say or write what someone or something is like.',
    textExample: 'They <b>described</b> their tree as colorful, with gold ribbon and a star.',
    transcription: '[diskráib]',
    textExampleTranslate: 'Они описали свое дерево как красочное, с золотой лентой и звездой',
    textMeaningTranslate: 'Описать - это сказать или написать, на что похож кто-то или что-то',
    wordTranslate: 'описать',
    wordsPerExampleSentence: 12,
  },
  {
    id: '5e9f5ee35eb9e72bc21af4cd',
    group: 0,
    page: 2,
    word: 'ever',
    image: 'files/03_0046.jpg',
    audio: 'files/03_0046.mp3',
    audioMeaning: 'files/03_0046_meaning.mp3',
    audioExample: 'files/03_0046_example.mp3',
    textMeaning: '<i>Ever</i> means at any time.',
    textExample: 'Going skiing last winter was the most fun I’ve <b>ever</b> had.',
    transcription: '[évər]',
    textExampleTranslate:
      'Кататься на лыжах прошлой зимой было самым веселым из всего, что я когда-либо ел',
    textMeaningTranslate: 'Всегда означает в любое время',
    wordTranslate: 'когда-либо',
    wordsPerExampleSentence: 11,
  },
  {
    id: '5e9f5ee35eb9e72bc21af4ce',
    group: 0,
    page: 2,
    word: 'fail',
    image: 'files/03_0047.jpg',
    audio: 'files/03_0047.mp3',
    audioMeaning: 'files/03_0047_meaning.mp3',
    audioExample: 'files/03_0047_example.mp3',
    textMeaning: 'To <i>fail</i> means you do not succeed in what you try to do.',
    textExample: 'Since he <b>failed</b> to get the job, he was sad.',
    transcription: '[feil]',
    textExampleTranslate: 'Так как он не смог получить работу, ему было грустно',
    textMeaningTranslate: 'Неудача означает, что вам не удается то, что вы пытаетесь сделать',
    wordTranslate: 'потерпеть поражение',
    wordsPerExampleSentence: 10,
  },
  {
    id: '5e9f5ee35eb9e72bc21af4cf',
    group: 0,
    page: 2,
    word: 'grade',
    image: 'files/03_0048.jpg',
    audio: 'files/03_0048.mp3',
    audioMeaning: 'files/03_0048_meaning.mp3',
    audioExample: 'files/03_0048_example.mp3',
    textMeaning: 'A <i>grade</i> is a score or mark given to someone’s work.',
    textExample: 'I managed to get good <b>grades</b> on my report card.',
    transcription: '[greid]',
    textExampleTranslate: 'Мне удалось получить хорошие оценки на моем табеле',
    textMeaningTranslate: 'Оценка - это оценка или оценка, присвоенная чьей-либо работе',
    wordTranslate: 'класс',
    wordsPerExampleSentence: 10,
  },
  {
    id: '5e9f5ee35eb9e72bc21af4d0',
    group: 0,
    page: 2,
    word: 'instead',
    image: 'files/03_0049.jpg',
    audio: 'files/03_0049.mp3',
    audioMeaning: 'files/03_0049_meaning.mp3',
    audioExample: 'files/03_0049_example.mp3',
    textMeaning: '<i>Instead</i> means in place of.',
    textExample: 'He ate the carrot <b>instead</b> of the ice cream.',
    transcription: '[instéd]',
    textExampleTranslate: 'Он съел морковку вместо мороженого',
    textMeaningTranslate: 'Вместо означает вместо',
    wordTranslate: 'вместо',
    wordsPerExampleSentence: 9,
  },
  {
    id: '5e9f5ee35eb9e72bc21af4d1',
    group: 0,
    page: 2,
    word: 'library',
    image: 'files/03_0050.jpg',
    audio: 'files/03_0050.mp3',
    audioMeaning: 'files/03_0050_meaning.mp3',
    audioExample: 'files/03_0050_example.mp3',
    textMeaning: 'A <i>library</i> is a place where you go to read books.',
    textExample: 'The <b>library</b> at school is full of books.',
    transcription: '[láibrèri]',
    textExampleTranslate: 'Библиотека в школе полна книг',
    textMeaningTranslate: 'Библиотека - это место, куда вы ходите читать книги',
    wordTranslate: 'библиотека',
    wordsPerExampleSentence: 8,
  },
];

export default GAME_DATA;
